name: Build and Deploy to dev environment

on:
  push:
    branches:
      - dev
      - COM-52

  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Login to google cloud
          uses: google-github-actions/auth@v2
          with:
            credentials_json: ${{ secrets.SERVICE_ACCOUNT }}

        - name: Deploy to Cloud Run
          uses: google-github-actions/deploy-cloudrun@v2
          with:
            service: catalog-api-dev
            image: ${{ vars.DOCKER_REGISTRY }}/catalog-api:dev-9958178894
            region: asian-southeast2
            flags: '--allow-unauthenticated --port=8080 --memory=256Mi --cpu=1 --min-instances=0 --max-instances=1 --cpu-throttling'
