name: Testcontainers tests

on:
  pull_request:
    types:
      - labeled
  push:
    branches:
      - dev
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-testing:
    if: ${{ github.event.label.name == 'run-test' || (github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.1
      - name: Run tests
        run: |
          make test
      - name: Remove label
        uses: actions-ecosystem/action-remove-labels@v1
        if: ${{always()}}
        with:
          label: run-test
          fail_on_error: false
