name: Run tests

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - master
      - dev
    paths-ignore:
      - '.github/**'
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-testing:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.1
      - name: Run tests
        run: |
          go test ./tests/... -v
      - name: Remove label
        uses: actions-ecosystem/action-remove-labels@v1
        if: ${{always()}}
        with:
          labels: run-test
          fail_on_error: false
